# Generated by Django 5.0.6 on 2024-06-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_session_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("paid", "PAID"),
                    ("expired", "EXPIRED"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
